---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-hogger
spec:
  selector:
    matchLabels:
      app: scalable-hogger
  template:
    metadata:
      labels:
        app: scalable-hogger
    spec:
      containers:
      - name: scalable-hogger
        image: docker.io/antonbiz/resource-hog:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: scalable-hogger-service
spec:
  selector:
    app: scalable-hogger
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scalable-hogger-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scalable-hogger-service
            port: 
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-hogger-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalable-hogger
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
